config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :leagues
  resources :teams
  resources :players
  resources :tournaments
  resources :matches
  resources :player_performances

  # Add any additional custom routes here
  root 'leagues#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/league.rb
class League < ApplicationRecord
  # belongs_to :admin, class_name: 'User', foreign_key: 'user_id'
  has_many :teams
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :tournament
  has_many :player_performances
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :team_players
  has_many :teams, through: :team_players
  has_many :player_performances
end

app/models/player_performance.rb
class PlayerPerformance < ApplicationRecord
  belongs_to :player
  belongs_to :match
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :league
  has_many :team_players
  has_many :players, through: :team_players
end

app/models/team_player.rb
class TeamPlayer < ApplicationRecord
  belongs_to :team
  belongs_to :player
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :matches
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :admin_leagues, class_name: 'League', foreign_key: 'user_id'
  has_many :teams
end

app/controllers/leagues_controller.rb
# app/controllers/leagues_controller.rb

class LeaguesController < ApplicationController
  def index
    @leagues = League.all
  end


  def new
    @league = League.new
  end

  
  # ...
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
end

app/controllers/player_performances_controller.rb
class PlayerPerformancesController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/player_performances_helper.rb
module PlayerPerformancesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/player_performances/_form.html.erb
<%= form_with(model: player_performance) do |form| %>
  <% if player_performance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player_performance.errors.count, "error") %> prohibited this player_performance from being saved:</h2>

      <ul>
        <% player_performance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/player_performances/_player_performance.html.erb
<div id="<%= dom_id player_performance %>">
</div>

app/views/player_performances/edit.html.erb
<h1>Editing player performance</h1>

<%= render "form", player_performance: @player_performance %>

<br>

<div>
  <%= link_to "Show this player performance", @player_performance %> |
  <%= link_to "Back to player performances", player_performances_path %>
</div>

app/views/player_performances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Player performances</h1>

<div id="player_performances">
  <% @player_performances.each do |player_performance| %>
    <%= render player_performance %>
    <p>
      <%= link_to "Show this player performance", player_performance %>
    </p>
  <% end %>
</div>

<%= link_to "New player performance", new_player_performance_path %>

app/views/player_performances/new.html.erb
<h1>New player performance</h1>

<%= render "form", player_performance: @player_performance %>

<br>

<div>
  <%= link_to "Back to player performances", player_performances_path %>
</div>

app/views/player_performances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player_performance %>

<div>
  <%= link_to "Edit this player performance", edit_player_performance_path(@player_performance) %> |
  <%= link_to "Back to player performances", player_performances_path %>

  <%= button_to "Destroy this player performance", @player_performance, method: :delete %>
</div>